// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLo1HXMen-HHM3iunmnHj0SeZAtoGDIc',
    appId: '1:389954890075:web:63700bcbd8076b3e61d27e',
    messagingSenderId: '389954890075',
    projectId: 'mosquito-6e8b4',
    authDomain: 'mosquito-6e8b4.firebaseapp.com',
    storageBucket: 'mosquito-6e8b4.appspot.com',
    measurementId: 'G-KQ1MFE6XJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0SZMaL2RR-JplXw0JJQPRyIftkmRVxFA',
    appId: '1:389954890075:android:2edf8bbb670bf25761d27e',
    messagingSenderId: '389954890075',
    projectId: 'mosquito-6e8b4',
    storageBucket: 'mosquito-6e8b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Rmee6U9NamWU1xnFaw5PWMJfpef2yHs',
    appId: '1:389954890075:ios:2b8f172b0943d35161d27e',
    messagingSenderId: '389954890075',
    projectId: 'mosquito-6e8b4',
    storageBucket: 'mosquito-6e8b4.appspot.com',
    iosClientId: '389954890075-fgumsjm9q78l4r3vupmvecvshshmpdkb.apps.googleusercontent.com',
    iosBundleId: 'com.mosquito.mosquito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Rmee6U9NamWU1xnFaw5PWMJfpef2yHs',
    appId: '1:389954890075:ios:2b8f172b0943d35161d27e',
    messagingSenderId: '389954890075',
    projectId: 'mosquito-6e8b4',
    storageBucket: 'mosquito-6e8b4.appspot.com',
    iosClientId: '389954890075-fgumsjm9q78l4r3vupmvecvshshmpdkb.apps.googleusercontent.com',
    iosBundleId: 'com.mosquito.mosquito',
  );
}
